const $=id=>document.getElementById(id),KEY="myGarage.v1";let cars=JSON.parse(localStorage.getItem(KEY)||"[]"),activeCarId=null,editingWorkId=null;
const money=n=>new Intl.NumberFormat("uk-UA").format(n||0)+" ₴";const fmt=n=>new Intl.NumberFormat("uk-UA").format(n||0);
function save(){localStorage.setItem(KEY,JSON.stringify(cars));render()}
function render(){ $("carCount").textContent=cars.length; $("totalCost").textContent=money(cars.reduce((s,c)=>s+(c.works||[]).reduce((a,w)=>a+(+w.cost||0),0),0)); $("cars").innerHTML=cars.map(c=>{const total=(c.works||[]).reduce((s,w)=>s+(+w.cost||0),0);return `<article class="car" data-id="${c.id}"><div class="car-head"><div><div class="eyebrow">${c.owner||"ВЛАСНИК"}</div><h2>${c.name}</h2><span class="muted">${[c.year,c.engine,c.gearbox].filter(Boolean).join(" · ")}</span></div><span class="badge">${(c.works||[]).length} роб.</span></div><div class="mileage">${fmt(c.mileage)} <small>км</small></div><span class="muted">поточний пробіг</span><div class="stats"><span>Витрати<br><b>${money(total)}</b></span><span>Остання робота<br><b>${c.works?.length?fmt(Math.max(...c.works.map(w=>+w.mileage||0)))+" км":"—"}</b></span></div></article>`}).join(""); $("empty").classList.toggle("hidden",cars.length>0); document.querySelectorAll(".car").forEach(x=>x.onclick=()=>view(x.dataset.id)) }
function view(id){activeCarId=id;const c=cars.find(x=>x.id===id),works=[...(c.works||[])].sort((a,b)=>(+b.mileage||0)-(+a.mileage||0));$("carView").innerHTML=`<div class="eyebrow">${c.owner||"ВЛАСНИК"}</div><h2>${c.name}</h2><div class="mileage">${fmt(c.mileage)} км</div><p class="muted">${[c.year,c.engine,c.gearbox].filter(Boolean).join(" · ")}</p><button class="primary add-work" id="addWork">＋ Додати роботу</button><div class="section-head"><h3>Історія робіт</h3><span class="muted">${works.length} записів</span></div><div class="history">${works.map(w=>`<div class="work"><div class="work-top"><div><b>${w.title}</b><span class="muted">${w.date||"Без дати"} · ${fmt(w.mileage)} км</span></div><div class="work-actions"><button data-edit="${w.id}">✎</button><button data-delete="${w.id}">×</button></div></div>${w.parts?`<div><strong>Запчастини:</strong> ${w.parts}</div>`:""}${w.cost?`<div><strong>Вартість:</strong> ${money(w.cost)}</div>`:""}${w.note?`<div class="muted note">${w.note}</div>`:""}</div>`).join("")||"<p class=\"muted\">Поки немає записів.</p>"}</div>`;const editBtn=document.createElement("button");editBtn.className="secondary";editBtn.textContent="✎ Редагувати авто";editBtn.onclick=()=>openEditCar();$("carView").prepend(editBtn);$("addWork").onclick=()=>openWork();document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=e=>{e.stopPropagation();openWork(b.dataset.edit)});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=e=>{e.stopPropagation();deleteWork(b.dataset.delete)});$("carViewDialog").showModal()}
function openWork(id=null){editingWorkId=id;const c=cars.find(x=>x.id===activeCarId),w=id?(c.works||[]).find(x=>x.id===id):null,f=$("workForm");f.reset();$("workDialogTitle").textContent=w?"Редагувати роботу":"Додати роботу";f.elements.title.value=w?.title||"";f.elements.date.value=w?.date||new Date().toISOString().slice(0,10);f.elements.mileage.value=w?.mileage??c.mileage??"";f.elements.parts.value=w?.parts||"";f.elements.cost.value=w?.cost??"";f.elements.note.value=w?.note||"";$("workDialog").showModal()}
function deleteWork(id){if(!confirm("Видалити цей запис про роботу?"))return;const c=cars.find(x=>x.id===activeCarId);c.works=(c.works||[]).filter(w=>w.id!==id);save();view(activeCarId)}
$("addCar").onclick=$("addCarEmpty").onclick=()=>$("carDialog").showModal();$("closeCar").onclick=()=>$("carDialog").close();$("closeView").onclick=()=>$("carViewDialog").close();$("closeWork").onclick=()=>$("workDialog").close();
$("carForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);cars.push({id:crypto.randomUUID(),name:f.get("name"),year:f.get("year"),mileage:+f.get("mileage")||0,engine:f.get("engine"),gearbox:f.get("gearbox"),owner:f.get("owner"),works:[]});save();e.target.reset();$("carDialog").close()};
$("workForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),c=cars.find(x=>x.id===activeCarId),w={id:editingWorkId||crypto.randomUUID(),title:f.get("title"),date:f.get("date"),mileage:+f.get("mileage")||0,parts:f.get("parts"),cost:+f.get("cost")||0,note:f.get("note")};c.works=c.works||[];const i=c.works.findIndex(x=>x.id===w.id);if(i>=0)c.works[i]=w;else c.works.push(w);save();$("workDialog").close();view(activeCarId)};render();
function openEditCar(){const c=cars.find(x=>x.id===activeCarId),f=$("editCarForm");f.elements.name.value=c.name||"";f.elements.year.value=c.year||"";f.elements.mileage.value=c.mileage||"";f.elements.engine.value=c.engine||"";f.elements.gearbox.value=c.gearbox||"";f.elements.owner.value=c.owner||"";f.elements.vin.value=c.vin||"";f.elements.plate.value=c.plate||"";f.elements.photo.value=c.photo||"";$("editCarDialog").showModal()}
$("closeEditCar").onclick=()=>$("editCarDialog").close();
$("editCarForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),c=cars.find(x=>x.id===activeCarId);c.name=f.get("name");c.year=f.get("year");c.mileage=+f.get("mileage")||0;c.engine=f.get("engine");c.gearbox=f.get("gearbox");c.owner=f.get("owner");c.vin=f.get("vin");c.plate=f.get("plate");c.photo=f.get("photo");save();$("editCarDialog").close();$("carViewDialog").close()};
$("deleteCar").onclick=()=>{if(!confirm("Видалити автомобіль разом з усією історією робіт?"))return;cars=cars.filter(c=>c.id!==activeCarId);save();$("editCarDialog").close();$("carViewDialog").close()};